version: "3.8"

services:

  frontend:
    container_name: ict381web
    image: ict381
    build: .
    networks:
      - ict381network
    ports:
      - "5000:5000"

  db:
    container_name: ict381db
    image: mongo
    networks:
      - ict381network
    ports:
      - "27017:27017"

networks:
  ict381network:
  